### ISSUE TITLE
CNRM containercluster missing ipAllocationPolicy fields needed to create private GKE clusters

### ISSUE THREAD

**Issue by jlewi** [kubeflow/gcp-blueprints#32]
It looks like in CNRM 1.9.1 the CRD for container cluster is missing ipAllocationPolicy fields needed to
create a private GKE cluster.

To work around that; get the CRD and change the schema to be

```
...
              ipAllocationPolicy:
                properties:
                  useIpAliases:
                    type: boolean
                  createSubnetwork:
                    type: boolean
                  subnetworkName:
                    type: string
                  clusterIpv4CidrBlock:
                    type: string
                  clusterSecondaryRangeName:
                    type: string
                  servicesIpv4CidrBlock:
                    type: string
                  servicesSecondaryRangeName:
                    type: string
                type: object
...
```

**Comment by jlewi** [comment]
To edit the CRD:

1. Fetch the CRD
  
    ```
     kubectl get crd containerclusters.container.cnrm.cloud.google.com -o yaml > /tmp/container.crd.yaml
    ```

1. Open `/tmp/container.crd.yaml` and edit the schema to set ipallocationpolicy as mentioned in the previous comment.

1. Apply it

    ```
     kubectl apply -f /tmp/container.crd.yaml
    ```

**Comment by jlewi** [comment]
Spoke to soon; doesn't look like this actually worked. The cluster ended up getting created on the default network; no subnetwork was created automatically.
https://gist.github.com/jlewi/29edc43a2b9cf7329f5274e7e35ad609

**Comment by parthmishra** [comment]
Is this still something that needs to be done? I wasn't sure if this was resolved already

**Comment by jlewi** [comment]
I'm hoping by now this is resolved in newer versions of CNRM but need to double check and then should update the documentation (kubeflow/website#2190) appropriately.

**Comment by Bobgy** [comment]
After upgrading CNRM to 0.29.0 in KF 1.2 management cluster. I believe the issue has been fixed.
https://github.com/kubeflow/gcp-blueprints/pull/152

Search for "ipAllocationPolicy" in https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster#spec

**Comment by TrsNium** [comment]
@Bodgy
Hello. The above problem is not yet solved.
I installed cnrm based on the changes that have been incorporated into the master branch, but the same error as above occurred.
```
Error from server: error when creating ".build/gcp_config/container.cnrm.cloud.google.com_v1beta1_containercluster_kubeflow.yaml": admission webhook "deny-unknown-fields.cnrm.cloud.google.com" denied the request: unknown field "spec.ipAllocationPolicy.createSubnetwork"
make: *** [apply-gcp] Error 1
```

**Comment by Bobgy** [comment]
@TrsNium you are right. I didn't realize `createSubnetwork` field is not in the spec.

It doesn't seem like adding those fields will help.
I think this problem needs to be solved in the upstream repo. Has anyone created an issue there?

**Comment by Bobgy** [comment]
https://github.com/GoogleCloudPlatform/k8s-config-connector

**Comment by RoyerRamirez** [comment]
Hi has this issue been resolved? If not, we might be able to assists if we get more context into what's needed to get this up and running? All the GKE clusters we run are private cluster.

Best,

Royer R Ruiz
